source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

targetsArray = ['DemoMVVM', 'BlogMVVM']

targetsArray.each do |t|
    
    target t do
        pod 'ReactiveCocoa','2.5'
        pod 'AFNetworking'
        pod 'MBProgressHUD'
        pod 'MJExtension'
        pod 'MJRefresh'
    end
    
end

